title: My Jekyll Site Sample
description: A brief description of my site
baseurl: "/myjekyllsite" # If applicable
permalink: /:title/
collections:
  events:
    output: true
    permalink: /events/:title/
  blog:
    output: true
    permalink: /blog/:title/