title: My Jekyll Site Sample
description: A brief description of my site.
url: "https://pompy.github.io/"
baseurl: "/jekyllsite" # If applicable
permalink: /:title/
collections:
  events:
    output: true
    permalink: /events/:title/
  blog:
    output: true
    permalink: /blog/:title/